# Generated by Django 4.2 on 2023-04-06 07:22

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleOfVaak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(1, 'Team'), (2, 'Directors')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to=map.models.user_directory_path)),
                ('designation', models.TextField()),
            ],
        ),
    ]
